services:
  backend:
    build:
      context: ./ic-backend
      dockerfile: Dockerfile
    container_name: ic-backend
    ports:
      - "8000:8000"
    volumes:
      - ./ic-backend:/var/www
      - ./logs/xdebug:/var/log
    environment:
      - APP_ENV=local
      - APP_KEY=base64:R9KgY5mYckS0obzLMvDUOC5PBGp8qc9HuaC7Js/bsxM=
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=ic-database
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db
    # command: sh -c "sleep 10 && php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"


  frontend:
    build:
      context: ./ic-frontend
      dockerfile: Dockerfile
    container_name: ic-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./ic-frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: ng serve --host 0.0.0.0 --port 4200 --poll=2000
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: investcontrol-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ic-database
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
